backend:
  name: github
  repo: huhlawat/huhlawat.github.io
  branch: main
  auth_type: pkce
  app_id: Ov23liaNeSMRQNpfFmQg

media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Work"
        name: "work"
        file: "content/work/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "content/contact/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
